#!/usr/bin/env python3
"""Generate data/languages/ppc_32_e200.pspec.

SPR numbers come from NXP's e200 GNU tools (gdb power-e200sprs.xml, where register
number = SPR number + 100, and the binutils SPR names for mfspr/mtspr), plus
AN12177 for MPU0CSR0. Names follow the e200 core reference manuals.

usage: gen_pspec.py [--check]
  --check  exit with status 1 if ppc_32_e200.pspec is not up to date
"""
import re
import sys
from pathlib import Path

LANG = Path(__file__).resolve().parent.parent / "data" / "languages"

E200Z4_SPRS = {
    1: "XER", 8: "LR", 9: "CTR",
    22: "DEC", 26: "SRR0", 27: "SRR1", 48: "PID0", 54: "DECAR",
    58: "CSRR0", 59: "CSRR1", 61: "DEAR", 62: "ESR", 63: "IVPR",
    256: "USPRG0", 268: "TBL", 269: "TBU",
    272: "SPRG0", 273: "SPRG1", 274: "SPRG2", 275: "SPRG3",
    276: "SPRG4", 277: "SPRG5", 278: "SPRG6", 279: "SPRG7",
    284: "TBL", 285: "TBU", 286: "PIR", 287: "PVR",
    304: "DBSR", 308: "DBCR0", 309: "DBCR1", 310: "DBCR2",
    312: "IAC1", 313: "IAC2", 314: "IAC3", 315: "IAC4",
    316: "DAC1", 317: "DAC2", 318: "DVC1", 319: "DVC2",
    336: "TSR", 340: "TCR",
    **{400 + i: f"IVOR{i}" for i in range(16)},
    512: "SPEFSCR", 515: "L1CFG0", 516: "L1CFG1",
    528: "IVOR32", 529: "IVOR33", 530: "IVOR34", 531: "IVOR35",
    560: "CTXCR", 561: "DBCR3", 562: "DBCNT", 563: "DBCR4", 564: "DBCR5",
    565: "IAC5", 566: "IAC6", 567: "IAC7", 568: "IAC8", 569: "DBERC0",
    570: "MCSRR0", 571: "MCSRR1", 572: "MCSR", 573: "MCAR",
    574: "DSRR0", 575: "DSRR1", 576: "DDAM",
    603: "DBCR6", 604: "SPRG8", 605: "SPRG9",
    624: "MAS0", 625: "MAS1", 626: "MAS2", 627: "MAS3", 628: "MAS4", 630: "MAS6",
    688: "TLB0CFG", 689: "TLB1CFG", 959: "L1FINV1",
    1008: "HID0", 1009: "HID1", 1010: "L1CSR0", 1011: "L1CSR1", 1012: "MMUCSR0",
    1013: "BUCSR", 1014: "MPU0CSR0", 1015: "MMUCFG", 1016: "L1FINV0", 1023: "SVR",
}

# Timebase reads change on every access.
VOLATILE = {"TBLr", "TBUr", "TBLw", "TBUw"}

# SPRs the hardware changes between accesses. Without this the decompiler propagates a
# value the code wrote into a later read and removes the polling loops of startup code as
# unreachable, for example the wait for L1CSR1[ICINV] or BUCSR[BBFI] to clear.
VOLATILE_SPRS = {
    22,                  # DEC: counts down
    304, 336, 572,       # DBSR, TSR, MCSR: status bits set by hardware, cleared by writing 1
    624, 625, 626, 627,  # MAS0-MAS3: filled by mpure
    1010, 1011, 1013,    # L1CSR0, L1CSR1, BUCSR: invalidate and abort bits clear themselves
    1012, 1014,          # MMUCSR0, MPU0CSR0: invalidate bits clear themselves
}


def sleigh_spr_names():
    """SPR register names in SLEIGH order, as defined by Ghidra's ppc_common.sinc."""
    text = (LANG / "ppc_common.sinc").read_text()
    i = text.index("spr000")
    body = text[text.rindex("[", 0, i) + 1:text.index("];", i)]
    names = re.findall(r"[A-Za-z_][A-Za-z0-9_]*", body)
    assert len(names) == 1024, len(names)
    return names


def main():
    lines = []
    for number, sleigh in enumerate(sleigh_spr_names()):
        attrs = [f'name="{sleigh}"']
        name = E200Z4_SPRS.get(number)
        if name and name != sleigh and not sleigh.startswith("TB"):
            attrs.append(f'rename="{name}"')
        attrs.append(f'group="{"SPR" if name else "SPR_UNNAMED"}"')
        if sleigh in VOLATILE:
            attrs.append('volatile="true"')
        comment = f"  <!-- SPR {number} -->" if name else ""
        lines.append(f"    <register {' '.join(attrs)}/>{comment}")

    # SPR n is at 0x1000 + 4n in the register space of ppc_common.sinc (32-bit registers)
    volatile = [f'    <range space="register" first="0x{0x1000 + 4 * n:x}" last="0x{0x1003 + 4 * n:x}"/>'
                f'  <!-- {E200Z4_SPRS[n]} -->' for n in sorted(VOLATILE_SPRS)]

    pspec = f"""<?xml version="1.0" encoding="UTF-8"?>

<!-- Generated by tools/gen_pspec.py; edit that script instead. -->
<processor_spec>
  <properties>
    <property key="addressesDoNotAppearDirectlyInCode" value="true"/>
    <!-- No emulateInstructionStateModifierClass: Ghidra's PPCEmulateInstructionStateModifier
         only adds AltiVec vperm, which the e200 lacks, and is in the stock PowerPC module,
         without which the emulator refused to start for this language. -->
    <property key="useropLibs" value="ppc"/>
    <!-- Replaced by the PowerPC e200 Constant Reference Analyzer of this extension -->
    <property key="Analyzers.PowerPC Constant Reference Analyzer" value="false"/>
    <!-- Function prototypes from the decompiler (Ghidra enables it only for Windows programs):
         parameter and return types, fewer undefined variables and casts -->
    <property key="Analyzers.Decompiler Parameter ID" value="true"/>
  </properties>

  <programcounter register="pc"/>

  <!-- e200z4 cores in MPC57xx devices execute VLE only. -->
  <context_data>
    <context_set space="ram">
      <set name="vle" val="1"/>
      <set name="linkreg" val="0"/>
    </context_set>
  </context_data>

  <!-- SPRs the hardware changes between accesses (see VOLATILE_SPRS). Given as register
       space ranges: the volatile attribute of a renamed register breaks the decompiler. -->
  <volatile outputop="write_volatile" inputop="read_volatile">
{chr(10).join(volatile)}
  </volatile>

  <!-- e200z4 special purpose registers. Unnamed SPRs keep their sprNNN names. -->
  <register_data>
{chr(10).join(lines)}
  </register_data>
</processor_spec>
"""
    out = LANG / "ppc_32_e200.pspec"
    if "--check" in sys.argv[1:]:
        if not out.exists() or out.read_text() != pspec:
            print(f"{out} is out of date; run {Path(__file__).name}")
            sys.exit(1)
        return
    out.write_text(pspec, newline="\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
